---
title: "Intro"
author: "W. McDonald"
date: "11/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The Classification Problem in Pituitary Adenoma: The Role of Tpit Immunohistochemistry

## Intro ideas
Pituitary adenoma classification suffers from a variety of problems. Initially developed with electron microscopy in mind, the World Health Organization classification retains many of the vestiges of those early studies and their problems: small numbers, small samples, with the most important series apparently jumping primary literature for publication in textbooks. Further adding to the confusion, no one seems to use the classification, preferring instead to apply simpler classifications (refs, especially Asa and Mete's epidemilogy paper, the German series, any French series). 

The resulting WHO classification has been difficult to refine, even  with the advent of new IHC for transcription factors. Substantive arguments about prevalence and classification are avoided in favor of unimportant nomenclature changes (pituitary neuroendocrine tumor or PitNET is neither more brief nor more useful than its precursor, but it enjoys the praise of endocrine pathologists, and it sounds clever. Cleverness notwithstanding, it fails to clarify the fundamental problem of classification. 

We published a series of 136 PitNETs in 2017 in an attempt to improve the situation. At the time, reagents suitable for formalin-fixed, paraffin-embedded material were available for only Steroidogenic Factor 1 and Pit-1. Nonetheless, we were able to show great improvements, both in diagnostic efficiency and diagnostic accuracy, and related a simple algorithm that was sufficient to classify most PitNETs with three IHC stains. 

Pituitary adenomas can be classified in three broad families based on their resemblance to developmental pathways of the anterior pituitary (1). While immunohistochemical stains for the six anterior pituitary hormones (prolactin, growth hormone, thyroid stimulating hormone, luteinizing hormone, follicle stimulating hormone and adrenocorticotropin (ACTH)) are widely used, some of these suffer from suboptimal sensitivity and specificity. ACTH immunoreactivity in particular is widely regarded as lacking in sensitivity and specificity. This is problematic, since ACTH-producing macroadenomas are considered more aggressive (2), and the resection of hormonally active ACTH-producing tumors can cause life-threatening cortisol insufficiency if left untreated. That is, both over- and under-detection of ACTH-producing tumors can have clinical consequences. 

ACTH-producing adenomas account for approximately 17% of pituitary adenomas (3) . T-box transcription factor (T-Pit) mediates the corticotroph pathway (4, 5). Until recently, immunostains for T-Pit were restricted to frozen material, but the introduction of a polyclonal antibody to T-pit developed and validated according to standardized procedures within the Human Protein Atlas (http://www.proteinatlas.org) provides a reagent that reportedly overcomes this restriction. 

In this work, we use T-Pit IHC in conjunction with IHC for SF-1 and Pit-1 to classify pituitary adenomas. According to Sjostedt et al. (6), T-Pit IHC is more sensitive and specific than ACTH IHC. Our findings in this series support this assertion. 